baseURL = "https://www.MountainTopLLC.org/"
languageCode = "en-us"
title = "MountainTop LLC"
themesDir = "../.."
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "29px"
    mobile_width = "29px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "MountainTop LLC"

  [params.homepage_meta_tags]
    meta_description = "MountainTop LLC is your choice for Semi Truck Freight Delivery."
    meta_og_title = "MountainTop LLC"
    meta_og_type = "website"
    meta_og_url = "https://www.MountainTopLLC.org"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "MountainTop LLC is your choice for Semi Truck Freight Delivery."
    meta_twitter_card = "summary"
    meta_twitter_site = "@4MountainTopLLC"
    meta_twitter_creator = "@4MountainTopLLC"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
